package patches.buildTypes

import jetbrains.buildServer.configs.kotlin.v2018_1.*
import jetbrains.buildServer.configs.kotlin.v2018_1.BuildType
import jetbrains.buildServer.configs.kotlin.v2018_1.buildSteps.powerShell
import jetbrains.buildServer.configs.kotlin.v2018_1.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, create a buildType with absolute id = 'Prism_TestPsFail'
in the root project, and delete the patch script.
*/
create(DslContext.projectId, BuildType({
    id = AbsoluteId("Prism_TestPsFail")
    name = "test_ps_fail"

    steps {
        powerShell {
            scriptMode = script {
                content = """
                    Set-StrictMode -Version 2
                    ${'$'}ErrorActionPreference = "Stop"
                    set-psdebug -trace 2
                    
                    
                    echo "correct command"
                    echo "asd"
                    echo ${'$'}?
                    echo "incorrect command"
                    echo ${'$'}?
                    #if (${'$'}?) {
                    #  exit 1
                    #}
                """.trimIndent()
            }
        }
    }
}))

